version: "3.9"
services:

  youtube_comments:
    hostname: youtube_comments
    build: ./python_script
    container_name: youtube_comments
    volumes:
      - ./python_script/script.py:/app/script.py
    tty: true
    stdin_open: true
    secrets: 
      - youtube_api_key
    entrypoint: ["python", "script.py"]
    depends_on:
      logstash:
        condition: service_started

  logstash:
    hostname: logstash-container
    image: docker.elastic.co/logstash/logstash:8.13.0
    container_name: logstash-container
    environment:
      XPACK_MONITORING_ENABLED: "false"
    ports:
      - 9090:9090
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
  
secrets:
  youtube_api_key:
    file: ./python_script/.secret